# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'
pod 'Firebase/Firestore', '~> 5.15.0'
pod 'Firebase/Database', '~> 5.15.0'

target 'GameApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameApp


  target 'GameAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GameApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameApp-tvOS

  target 'GameApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
